# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("dek", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(default="Manufacturing insights", max_length=80),
                ),
                ("author", models.CharField(default="Trooba Team", max_length=120)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("read_time", models.CharField(blank=True, max_length=40)),
                ("cover_url", models.CharField(blank=True, max_length=500)),
                ("cover_alt", models.CharField(blank=True, max_length=255)),
                ("body_html", models.TextField(blank=True)),
                ("seo", models.JSONField(default=dict)),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "-published_at", "-id"],
            },
        ),
    ]
